define([],
    function () {

        return {
            Field: {
                COMPANY: 'company',
                END_DATE: 'enddate',
                FORMULA_CURRENCY: 'formulacurrency',
                INTERNAL_ID: 'internalid',
                IS_INACTIVE: 'isinactive',
                IS_QUARTER: 'isquarter',
                IS_YEAR: 'isyear',
                NAME: 'name',
                PERIOD_NAME: 'periodname',
                START_DATE: 'startdate',
                SCRIPT_ID: 'scriptid',
                TITLE: 'title'
            },
            AddressField: {
                ADDR1: 'addr1',
                ADDR2: 'addr2',
                ADDR3: 'addr3',
                ADDRESSEE: 'addressee',
                PHONE: 'addrphone',
                ATTENTION: 'attention',
                CITY: 'city',
                COUNTRY: 'country',
                STATE: 'state',
                ZIP: 'zip'
            },
            CrmField: {
                INTERNAL_ID: 'internalid',
                RECORD_TYPE: 'recordtype',
                STATUS: 'status',
                START_DATE: 'startdate',
                END_DATE: 'enddate',
                START_TIME: 'starttime',
                PROJECT: 'project',
                PROJECT_TASK: 'projecttask',
                PROJECT_NAME: 'projectname',
                NOTES: 'notes',
                MEMO: 'memo',
                RESOURCE: 'resource',
                REQUESTED_BY: 'requestedby',
                CUSTOMER: 'customer',
                COMPANY: 'company',
                CONTACT: 'contact',
                EMAIL: 'email',
                ASSIGNED: 'assigned',
                ORIGIN: 'origin',
                NUMBER_HOURS: 'numberhours',
                PERCENT_OF_TIME: 'percentoftime',
                APPROVAL_STATUS: 'approvalstatus',
                ALLOCATION_RESOURCE: 'allocationresource',
                ALLOCATION_AMOUNT: 'allocationamount',
                ALLOCATION_TYPE: 'allocationtype',
                ALLOCATION_UNIT: 'allocationunit'
            },
            TransactionField: {
                ACCOUNT: 'account',
                AMOUNT_PAID: 'amountpaid',
                APPROVAL_STATUS: 'approvalstatus',
                APPLIED_AMOUNT: 'applied',
                AR_ACCOUNT: 'aracct',
                ASSEMBLY_ITEM: 'assemblyitem',
                AUTOAPPLY: 'autoapply',
                CASE_TASK_EVENT: 'casetaskevent',
                CLASS: 'class',
                COMPONENT_INVENTORY_DETAIL: 'componentinventorydetail',
                CREATED_FROM: 'createdfrom',
                CURRENCY: 'currency',
                CUSTOM_FORM: 'customform',
                CUSTOMER: 'customer',
                DATE: 'date',
                DEPARTMENT: 'department',
                EMPLOYEE: 'employee',
                END_DATE: 'enddate',
                ENTITY: 'entity',
                ENTITY_STATUS: 'entitystatus',
                EXCHANGE_RATE: 'exchangerate',
                HOURS: 'hours',
                INTERNAL_ID: 'internalid',
                IS_BILLABLE: 'isbillable',
                IS_PRODUCTIVE: 'isproductive',
                INCOTERM: 'incoterm',
                ITEM: 'item',
                INVENTORY_DETAIL: 'inventorydetail',
                JOB: 'job',
                LANDED_COST: 'landedcost',
                LANDED_COST_PER_LINE: 'landedcostperline',
                LOCATION: 'location',
                MAINLINE: 'mainline',
                MEMO: 'memo',
                NEXT_APPROVER: 'nextapprover',
                ORDER_STATUS: 'orderstatus',
                PAYMENT_AMOUNT: 'payment',
                PAYMENT_METHOD: 'paymentmethod',
                PHANTOM_SUBASSEMBLIES: 'expandassembly',
                POSTING: 'posting',
                POSTING_PERIOD: 'postingperiod',
                QUANTITY: 'quantity',
                SERIAL_NUMBERS: 'serialnumbers',
                SHIPPING_ADDRESS: 'shippingaddress',
                SHIP_ADDRESS_LIST: 'shipaddresslist',
                START_DATE: 'startdate',
                STATUS: 'status',
                STATUS_REF: 'statusRef',
                SUBSIDIARY: 'subsidiary',
                TRAN_DATE: 'trandate',
                TRAN_ID: 'tranid',
                TRANSFER_LOCATION: 'transferlocation',
                TYPE: 'type',
                TOTAL: 'total',
                UNDEPFUNDS_ACCOUNT: 'undepfunds',
                USE_TEM_COST: 'useitemcostastransfercost'
            },
            EntityField: {
                ALLOW_EXPENSES: 'allowexpenses',
                ALLOW_TASK_TIME_FOR_RESOURCE_ALLOC: 'allowtasktimeforrsrcalloc',
                ALLOW_TIME: 'allowtime',
                ALLOW_RESOURCES_FOR_TASKS: 'allowallresourcesfortasks',
                ALT_PHONE: 'altphone',
                BILLING_TYPE: 'jobbillingtype',
                BILLING_SCHEDULE: 'billingschedule',
                CATEGORY: 'category',
                CLASS: 'class',
                COMPANY: 'company',
                COMPANY_NAME: 'companyname',
                DEPARTMENT: 'department',
                EMAIL: 'email',
                ENTITY_ID: 'entityid',
                ESTIMATED_LABOR_COST: 'estimatedlaborcost',
                ESTIMATED_LABOR_REVENUE: 'estimatedlaborrevenue',
                FAX: 'fax',
                FIRST_NAME: 'firstname',
                INTERNAL_ID: 'internalid',
                IS_INACTIVE: 'isinactive',
                IS_UTILIZED: 'isutilizedtime',
                IS_PRODUCTIVE: 'isproductivetime',
                IS_EXEMPT: 'isexempttime',
                JOB_TITLE: 'title',
                LAST_NAME: 'lastname',
                LIMIT_TIME_TO_ASSIGNEES: 'limittimetoassignees',
                LOCATION: 'location',
                MATERIALIZE_TIME: 'materializetime',
                PARENT: 'parent',
                PARTNER: 'partner',
                PHONE: 'phone',
                SALES_REP: 'salesrep',
                SHIP_ADDRESS: 'shipaddress',
                SHIP_ADDRESS1: 'shipaddress1',
                SHIP_ADDRESS2: 'shipaddress2',
                SHIP_ADDRESS3: 'shipaddress3',
                SHIP_ADDRESSEE: 'shipaddressee',
                SHIP_ATTENTION: 'shipattention',
                SHIP_CITY: 'shipcity',
                SHIP_COUNTRY_CODE: 'shipcountrycode',
                SHIP_STATE: 'shipstate',
                SHIP_PHONE: 'shipphone',
                SHIP_ZIP: 'shipzip',
                STATUS: 'entitystatus',
                SUBSIDIARY: 'subsidiary',
                TYPE: 'isperson',
                URL: 'url'
            },
            ItemField: {
                AVERAGE_COST: 'averagecost',
                BASE_PRICE: 'baseprice',
                DISPLAY_NAME: 'displayname',
                INTERNAL_ID: 'internalid',
                ITEM_ID: 'itemid',
                IS_INACTIVE: 'isinactive',
                LAST_COST: 'lastpurchaseprice',
                PRICING_GROUP: 'pricinggroup',
                PURCHASE_COST: 'cost',
                SUBTYPE: 'subtype',
                TYPE: 'type'
            },
            ItemNumberField: {
                INTERNAL_ID: 'internalid',
                IS_INACTIVE: 'isinactive',
                ITEM: 'item',
                LOCATION: 'location',
                QUANTITY_AVAILABLE: 'quantityavailable'
            },
            Sublist: {
                ADDRESS_BOOK: 'addressbook',
                APPLY: 'apply',
                COMPONENT: 'component',
                CREDIT: 'credit',
                EXPENSE: 'expense',
                INVENTORY_ASSIGNMENT: 'inventoryassignment',
                ITEM: 'item',
                ITEM_PRICING: 'itempricing',
                LANDED_COST: 'landedcostdata',
                LINE: 'line',
                LINKS: 'links',
                PRICE_1: 'price1',
                PURCHASE_ORDERS: 'purchaseorders'
            },
            SublistField: {
                ACCOUNT: 'account',
                AMOUNT: 'amount',
                APPLY: 'apply',
                ASSEMBLY_LEVEL:'assemblylevel',
                CATEGORY: 'category',
                CLASS: 'class',
                COST: 'costestimate',
                COST_OVERRIDE: 'unitcostoverride',
                CREDIT: 'credit',
                CREDIT_AMOUNT: 'creditamount',
                DEBIT: 'debit',
                DEBIT_AMOUNT: 'debitamount',
                DEPARTMENT: 'department',
                DESCRIPTION: 'description',
                DOCUMENT_NUMBER: 'doc',
                DUE: 'due',
                ENTITY: 'entity',
                GROSS_AMOUNT: 'grossamt',
                INTERNAL_ID: 'internalid',
                INVENTORY_DETAIL: 'inventorydetail',
                ISSUE_INVENTORY_NUMBER: 'issueinventorynumber',
                ID: 'id',
                ITEM: 'item',
                ITEM_DISPLAY: 'item_display',
                ITEM_RECEIVE: 'itemreceive',
                ITEM_TYPE: 'itemtype',
                ITEM_SUBTYPE: 'itemsubtype',
                LEVEL: 'level',
                LINE: 'line',
                LINE_UNIQUE_KEY: 'lineuniquekey',
                LINK_URL: 'linkurl',
                LOCATION: 'location',
                MEMO: 'memo',
                RECEIPT_INVENTORY_NUMBER: 'receiptinventorynumber',
                PO_AMOUNT: 'poamount',
                PO_DATE: 'podate',
                PO_ID: 'poid',
                PRICE: 'price',
                PRICE_1_: 'price_1_',
                QUANTITY: 'quantity',
                QUANTITY_COMMITTED: 'quantitycommitted',
                RATE: 'rate',
                SERIAL_NUMBERS: 'serialnumbers',
                TRAN_TYPE: 'trantype',
                TAX_CODE: 'taxcode',
                TAX_AMOUNT: 'tax1amt',
                TAX_ACCOUNT: 'tax1acct',
                TAX_RATE: 'taxrate1',
                TOTAL: 'total',
                UNITS: 'units'
            },
            WorkflowField: {
                CURRENT_STATE: 'currentstate'
            },
            Join: {
                CUSTOMER: 'customer',
                WORKFLOW: 'workflow'
            },
            TransactionTypeShort: {
                CREDITMEMO: 'CustCred',
                INVOICE: 'CustInvc',
                ITEMFULFILLMENT: 'ItemShip',
                ITEMRECEIPT: 'ItemRcpt',
                PURCHASEORDER: 'PurchOrd',
                RETURNAUTHORIZATION: 'RtnAuth',
                SALESORDER: 'SalesOrd',
                TRANSFERORDER: 'TrnfrOrd',
                VENDORBILL: 'VendBill',
                VENDORCREDIT: 'VendCred',
                WORKORDER: 'WorkOrd'
            },
            TransactionTypeName: {
                BILLCREDIT: 'Bill Credit',
                CREDITMEMO: 'Credit Memo',
                PURCHASEORDER: 'Purchase Order',
                SALESORDER: 'Sales Order',
                VENDORBILL: 'Vendor Bill',
                WORKORDER: 'Work Order'
            },
            TransactionTypeInternalId: {
                OPPORTUNITY: '37',
                PURCHASEORDER: '15',
                SALESORDER: '31',
                VENDORBILL: '17'
            },
            CheckBox: {
                TICKED: 'T',
                UNTICKED: 'F'
            },
            Role: {
                ADMINISTRATOR: '3'
            },
            Feature: {
                ONE_WORLD: 'SUBSIDIARIES',
                LOCATIONS: 'LOCATIONS'
            },
            Preference: {
                LANGUAGE: 'LANGUAGE'
            },
            User: {
                ROOT_ADMIN: '-5'
            },
            Mode: {
                COPY: 'copy',
                CREATE: 'create',
                EDIT: 'edit',
                TRANSFORM: 'transform'
            },
            ItemType: {
                ASSEMBLY: 'Assembly',
                INVENTORY: 'InvtPart',
                NON_INVENTORY: 'NonInvtPart',
                SERVICE_ITEM : 'Service',
                CHARGE_ITEM : 'OthCharge'
            },
            ItemTypeInternalId: {
                INVENTORY: '1',
                ASSEMBLY: '5'
            },
            ButtonId: {
                EDIT: 'edit'
            }
        }
    });